title = "Lagoon"
gitRepoUrl = "https://github.com/re-sync-dev/Lagoon" # From Git
gitSourceBranch = "main"
changelog = false

[docusaurus]
onBrokenLinks = "ignore"
onBrokenMarkdownLinks = "warn"

# From git:
url = "https://re-sync-dev.github.io"
projectName = "Lagoon"
baseUrl = "/Lagoon"
tagline = "The typesafe framework"

[navbar]
title = "Lagoon"

[home]
enabled = true
includeReadme = false

[footer]
style = "dark"
copyright = "Copyright Â© 2024 Re-Sync. Built with Moonwave and Docusaurus"
