[package]
name = "vyon/lagoon"
description = "Lagoon is a framework that is both barebones and portable."
version = "1.5.1"
registry = "https://github.com/UpliftGames/wally-index"
license = "MIT"
realm = "shared"
authors = ["Vyon (https://github.com/Vyon)"]

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.toml"]

[dependencies]
Signal = "data-oriented-house/lemonsignal@1.10.0"
